.i2dgraph_js_metadata <- function() {
deps_metadata <- list(`i2dgraph` = structure(list(name = "i2dgraph",
version = "0.0.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-interactive_2d_graph.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "i2dgraph",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`i2dgraph` = structure(list(name = "i2dgraph",
version = "0.0.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-interactive_2d_graph.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "i2dgraph",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`i2dgraph` = structure(list(name = "i2dgraph",
version = "0.0.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'i2dgraph.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "i2dgraph",
all_files = FALSE), class = "html_dependency"),
`i2dgraph` = structure(list(name = "i2dgraph",
version = "0.0.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'i2dgraph.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "i2dgraph",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
